export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOADING = 'LOADING';
export const STOP_LOADING= 'STOP_LOADING';
//USER LOADING
export const USER_LOADING = 'USER_LOADING';
export const USER_STOP_LOADING= 'USER_STOP_LOADING';
//USER TRANSACTION
export const CREATE_TRANSCATION= 'CREATE_TRANSCATION';
export const LIST_TRANSACTION= 'LIST_TRANSACTION';
//WALLET INFORMATION
export const WALLET_INFORMATION= 'WALLET_INFORMATION';
//ORDER INFORMATION
export const ORDER_INFORMATION= 'ORDER_INFORMATION';
//PRODUCT
export const GET_PRODUCTS= 'GET_PRODUCTS';

export const LIST_POPULAR= 'LIST_POPULAR';
export const POPULAR_LOADING= 'POPULAR_LOADING';
export const POPULAR_STOPLOADING= 'POPULAR_STOPLOADING';

export const LIST_BLOODTEST= 'LIST_BLOODTEST';
export const BLOODTEST_LOADING= 'BLOODTEST_LOADING';
export const BLOODTEST_STOPLOADING= 'BLOODTEST_STOPLOADING';

export const LIST_PACKAGE= 'LIST_PACKAGE';
export const PACKAGE_LOADING= 'PACKAGE_LOADING';
export const PACKAGE_STOPLOADING= 'PACKAGE_STOPLOADING';

export const LIST_REPORT= 'LIST_REPORT';
export const REPORT_LOADING= 'REPORT_LOADING';
export const REPORT_STOPLOADING= 'REPORT_STOPLOADING';

//Location Type
export const ADD_LOCATION = 'ADD_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const LIST_LOCATION = 'LIST_LOCATION';
export const LOCATION_LOADING = 'LOCATION_LOADING';
export const LOCATION_STOPLOADING = 'LOCATION_STOPLOADING';




